## Reaction Rates {#sec:reaction-rates}

A core concept in chemical kinetics is the idea of a **reaction rate** &mdash; the speed at which chemical change happens.
We express reaction rates mathematically as derivatives of the form $\frac{\mathrm{d}[\mathrm{X}]}{\mathrm{d}t}$, representing the change in concentration of a species X with time. This rate can be positive (for products being formed) or negative (for reactants being consumed).

For any reaction that does not have a 1:1 stoichiometry ratio between all reactants and products, the numerical &ldquo;rate&rdquo; will depend on the chemical species we choose to define this. For example, for the reaction

\begin{equation}
\mathrm{A} \longrightarrow 2\mathrm{B}
\end{equation}

the product, B, is formed at twice the rate that the reactant, A, is consumed.  Hence,

$$2\frac{\mathrm{d}[\mathrm{A}]}{\mathrm{d}t} = \frac{\mathrm{d}[\mathrm{B}]}{\mathrm{d}t}$$

In general, we can define an &ldquo;overall&rdquo; reaction rate $\nu$ that is related to the rates of change of reactants and products by

$$\nu = \frac{1}{n_\mathrm{X}}\frac{\mathrm{d}[\mathrm{X}]}{\mathrm{d}t}$$

where $n_\mathrm{X}$ is the stoichiometric coefficient of species $X$ in the reaction equation.
