## Simple Rate Equations

For many reactions, the rate of reaction is proportional to the concentrations of the reactants, raised to some power; i.e.,

$$\nu = k [\mathrm{A}]^a [\mathrm{B}]^b [\mathrm{C}]^c \ldots$$

The proportionality constant, $k$, is called the **rate constant**.
The exponents, $a$, $b$, $c$ &hellip;, describe the **order** of the reaction with respect to the reactants A, B, C &hellip;.

So, for a reaction

$$A + B \longrightarrow C$$

with rate equation (or &ldquo;rate law&rdquo;)

$$\nu = k[\mathrm{A}]^2[\mathrm{B}]$$,

we would describe this as being **second-order** with respect to A, and **first-order** with respect to B.

For rate equations that have the simple form above, we can define an **overall order**, which is the sum of the individual orders with respect to each of the reactants. In the example above, this reaction would be described as being **third-order** overall, since $a+b = 3$.

Not all reactions follow simple rate laws. For example, the reaction between H~2~ and Br~2~ to form HBr has an empirically-determined rate law

\begin{equation}
\nu = k\frac{[\mathrm{H}_2][\mathrm{Br}_2]^\frac{1}{2}}{1+k^\prime [\mathrm{HBr}]/[\mathrm{Br}_2]}
(\#eq:HBrratelaw)
\end{equation}

This rate law is first-order with respect to H~2~, because $\nu \propto [\mathrm{H_2}]$. But we cannot define an order with respect to Br~2~, because the overall rate is not simply proportional to $[\mathrm{Br}_2]$ raised to some power. Instead, we would describe the order with respect to Br~2~ as being undefined. This means the overall order is also undefined, since we cannot siply add the orders with respect to H~2~ and Br~2~.


